

spring:
  security:
    user:
      name: ${eureka-user.name}
      password: ${eureka-user.password}

eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  server:
    #是否开启自我保护（运行期间spring会统计信条失败的比例在15分钟之内是否低于85%，如果不低于85%，Eureka会将实例注册信息保护起来，让这些实例不会过期）
    enable-self-preservation: false
    #3秒钟自动剔除失效的节点
    eviction-interval-timer-in-ms: 3000
    #eureka server刷新readCacheMap的时间
    #注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    response-cache-update-interval-ms: 3000
  client:
    #获取实例时是否过滤，只保留UP状态的实例
    filter-only-up-instances: true
    #自己也注册到注册中心
    register-with-eureka: false
    #需要从其他eureka节点获取注册信息
    fetch-registry: false



