
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: 163_route
        uri: http://www.163.com/
        predicates:
        - Path=/163


ribbon:
  connect-imeout: 300     #创建连接的超时时间 单位：毫秒
  read-timeout: 2000      #处理请求的超时时间 单位：毫秒
  max-auto-retries-next-server: 0 #切换实例的重试次数
  max-auto-retries: 0     #对当前实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000   #hystrix线程超过3秒熔断，数值大于ribbon的处理超时时间，留给ribbon重试，否则直接熔断，重试就没有意义了
