

eureka-user:
  name: ddout
  password: ddout
  defaultZoneUrls: http://${eureka-user.name}:${eureka-user.password}@192.168.11.234:8700/eureka/


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-user.defaultZoneUrls}
    healthcheck:
        enabled: true

spring:
  security:
    user:
      name: ${eureka-user.name}
      password: ${eureka-user.password}
  rabbitmq:
    addresses: 192.168.11.234
    port: 5672
    username: sleuth
    password: sleuth
    virtual-host: sleuth
  sleuth:
    propagation-keys:
      - x-hyc-session-id
      - x-hyc-user-id
  datasource:
    name: mysqlds
    url: jdbc:mysql://192.168.11.234:3306/hyc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: "classpath:mapper/*.xml"

