

eureka-user:
  name: ddout
  password: ddout
  defaultZoneUrls: http://${eureka-user.name}:${eureka-user.password}@192.168.11.234:8700/eureka/


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-user.defaultZoneUrls}
    healthcheck:
        enabled: true

spring:
  security:
    user:
      name: ${eureka-user.name}
      password: ${eureka-user.password}
  rabbitmq:
    addresses: 192.168.11.234
    port: 5672
    username: sleuth
    password: sleuth
    virtual-host: sleuth
  sleuth:
    propagation-keys:
      - x-hyc-session-id
      - x-hyc-user-id
  datasource:
    url: jdbc:mysql://192.168.11.234:3306/hyc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

