
spring:  
  security:
    user:
      name: "monitor"
      password: "monitor"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS